### ISSUE TITLE
The `inspect` module **is** available in Py3.5

### ISSUE THREAD

**Issue by s0undt3ch** [mbarkhau/lib3to6#4]
Contrary to what ``lib3to6`` reports, the [inspect module is available on Py3.5](https://docs.python.org/3.5/library/inspect.html)

```
Traceback (most recent call last):
  File "/home/vampas/.cache/pre-commit/repokza_nfff/py_env-python3.7/bin/downgrade-source", line 8, in <module>
    sys.exit(main())
  File "/home/vampas/.cache/pre-commit/repokza_nfff/py_env-python3.7/lib/python3.7/site-packages/downgradesource/__main__.py", line 171, in main
    skip_black_formatting=options.no_black is True,
  File "/home/vampas/.cache/pre-commit/repokza_nfff/py_env-python3.7/lib/python3.7/site-packages/downgradesource/__main__.py", line 57, in untype_source
    fixed_source_text = transpile.transpile_module(ctx, source_text)
  File "/home/vampas/.cache/pre-commit/repokza_nfff/py_env-python3.7/lib/python3.7/site-packages/lib3to6/transpile.py", line 287, in transpile_module
    checker(ctx, module_tree)
  File "/home/vampas/.cache/pre-commit/repokza_nfff/py_env-python3.7/lib/python3.7/site-packages/lib3to6/checkers_backports.py", line 90, in __call__
    raise common.CheckError(errmsg, node)
lib3to6.common.CheckError: src/saltfactories/utils/__init__.py@7 - Prohibited import 'inspect'. This module is available since Python 3.6, but you configured target_version='3.5'. Use 'https://pypi.org/project/inspect2' instead
```

**Comment by mbarkhau** [comment]
It's even available on python2.7.

I can't remember what my thinking was. I may have taken the statement from the `inspect2` module. https://pypi.org/project/inspect2/

> A backport of the Python 3.6 inspect module to Python 2.7-3.5.

In other words, if you use `inspect2` then you can be sure on 2.7 - 3.5 that the semantics are the same going forward.
